apiVersion: v1
kind: Pod

metadata:
  name: pod-pv

spec:
  containers:
    - name: nginx-pv
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: volume-pvc



  volumes:
    - name: volume-pvc
      persistentVolumeClaim:
        claimName: exerc-pvc

        