apiVersion: v1
kind: Pod

metadata:
  name: sc-pod

spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: sc-volume

  volumes:
    - name: sc-volume
      persistentVolumeClaim:
        claimName: sc-pvc


