apiVersion: v1
kind: PersistentVolume
metadata:
  name: sc-peristence-volume
spec:
  capacity:
    storage:  8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  local:
    path: "/mnt/disk1"

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "israel-inspiron-5402"

